config/routes.rb
Depot::Application.routes.draw do
  resources :searches

  resources :questions

    get 'admin' => 'admin#index'

    controller :sessions do
        get 'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy
    end

    resources :users

    resources :orders
    resources :products
    resources :line_items
    resources :carts

    get "store/index"
    match '/store/index', to: "store#index"

    match '/all', to: 'search#index'
    match '/home', to: 'store#home'
    match '/contact', to: 'store#contact'

    resources :products do
        get :who_bought, on: :member
    end

    root to: 'store#index', as: 'store'

end

app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
  <title>Jewelry Online Store</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<!-- END:head -->
<body class="<%= controller.controller_name %>">
  <div id="banner">
    <%= image_tag("shoplogo.png", :size =>"100x40") %>
    <%= @page_title || "Jewelry Store" %>
  </div>
  
  <div id="columns">
    <div id="side">
    
    <% if !session[:user_id] %>
                  <%= button_to 'Login', login_url, method: :get, :class => 'button small matchblue' %>
                <% end %>
                
<!-- START_HIGHLIGHT -->
      <!-- START:hidden_div -->
<!-- START_HIGHLIGHT -->
      <% if @cart %>
<!-- END_HIGHLIGHT -->
        <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
          <%= render @cart %>
        <% end %>
<!-- START_HIGHLIGHT -->
      <% end %>
<!-- END_HIGHLIGHT -->
    <!-- END:hidden_div -->

                <ul>
                    <li><%= link_to "Home", "/"%></li>
                    <li><%= link_to "Search", new_search_path%></li>
                    <li><%= link_to "News", home_path %></li> 
                    <li><%= link_to "Contact", contact_path%></li>
                    <li><%= link_to "Questions", home_path %></li>
                    <li><%= link_to "All Products", all_path %></li>
                </ul>
                <!-- START_HIGHLIGHT -->



                <% if session[:user_id] %>
                    <ul>
                        <li><%= link_to 'Orders',   orders_path   %></li>
                        <li><%= link_to 'Products', products_path %></li>
                        <li><%= link_to 'Users',    users_path    %></li>
                    </ul>
                    <%= button_to 'Logout', logout_path, method: :delete , :class => 'button small matchblue' %>
                <% end %>
                
                 


                <%= form_tag :controller => 'store', :action =>'index', :method => 'get' do %>
                    <p>
                    <%= text_field_tag :search, params[:search], :id =>'search_field' %>
                    <%= submit_tag "Quick Search", :name => nil ,:class => 'button small matchblue' %>
                    <!--<%= link_to_function "Clear", "$('search_field').clear()" %> -->
                    </p>
                <% end %>
<!-- END_HIGHLIGHT -->

            </div>
            <div id="main">
                <%= yield %>
            </div>
        </div>
    </body>
</html>